### ISSUE TITLE
Project 3: Workflow, Adding CI to the Game

### ISSUE THREAD

**Issue by pravipati** [acme-hackathon/game#5]
## Prompt Title 

Workflow, Adding CI to the Game

## Prompt Description

One of the key benefits of using a modern version control platform is the ability to leverage continuous integration and continuous deployment. The second that someone on your team checks in code, you can kick off a set of processes and checks to run tests, lint your code, check for security vulnerabilities, and much more. Once those checks have passed, you can have your code deployed to a sandbox or production environment.
* Let’s pretend that your team wanted to adopt CI/CD in the next week—what would need to happen to make that a possibility? What tests / processes would need to run? How would you architect your deployment strategy? What is the closest that you could get to making your master branch “production ready”?

### Tasks

- [ ] Fork the built repo + complete Innersource Project 1 & 2 
- [ ] Install Azure Pipelines 
- [ ] Trigger tests from Protected Branches + add other rules 
- [ ] Add Codeowners 
- [ ] Fix the existing broken tests 

## Learning Outcomes

- [ ] Adding CI / CD
- [ ] How to use `CODEOWNERS`
- [ ] Using protected branches

## Technologies used

- Azure Pipelines
- GitHub branches

## Judging Criteria

See issue #1 .
